# Generated by Django 5.0.3 on 2024-03-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
